linters:
  enable:
    - gosimple
    - unused
    - typecheck
    - govet
    - errcheck
    - staticcheck
    - unused
    - revive
    - dupl
    - gocyclo
    - gofmt
    - misspell
    - gocritic
  enable-all: false
  disable-all: true
  fast: false

run:
  timeout: 3m

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unparam
        - staticcheck
